#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh"  # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

FONT="Hack Nerd Font"
FONT_SIZE=14.0
ICON_SIZE=16.0
BACKGROUND_HEIGHT=26
BACKGROUND_PADDING_RIGHT=5
LABEL_PADDING_RIGHT=10
ICON_PADDING=10
CORNER_RADIUS=8
SHADOW=off

sketchybar --bar height=25 \
	color=$TRANSPARENT \
	shadow=$SHADOW \
	position=bottom \
	sticky=on \
	padding_right=6 \
	padding_left=6 \
	y_offset=1 \
	margin=1 \
	blur_radius=20 \
	notch_width=200 

source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/username.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"
source "$ITEM_DIR/app_title.sh"

source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/input.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/weather.sh"
source "$ITEM_DIR/uptime.sh"
source "$ITEM_DIR/ip.sh"
source "$ITEM_DIR/network_down.sh"
source "$ITEM_DIR/network_up.sh"
source "$ITEM_DIR/disk.sh"
source "$ITEM_DIR/mem.sh"
source "$ITEM_DIR/cpu.sh"

sketchybar --update

echo "sketchybar configuration loaded.."
