#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh"  # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

FONT="Hack Nerd Font"
# SPACE_CLICK_SCRIPT="yabai -m space --focus \$SID 2>/dev/null" # The script that is run for clicking on space components

PADDINGS=1 # All paddings use this value (icon, label, background)

POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=8

CORNER_RADIUS=8
SHADOW=off

sketchybar --bar height=25 \
	color=$TRANSPARENT \
	shadow=$SHADOW \
	position=bottom \
	sticky=on \
	padding_right=6 \
	padding_left=6 \
	corner_radius=$CORNER_RADIUS \
	y_offset=1 \
	margin=1 \
	blur_radius=20 \
	notch_width=200 \
	--default updates=when_shown \
	icon.font="$FONT:Bold:14.0" \
	icon.color=$$WHITE \
	icon.padding_left=$PADDINGS \
	icon.padding_right=$PADDINGS \
	label.font="$FONT:SemiBold:13.0" \
	label.color=$WHITE \
	label.padding_left=$PADDINGS \
	label.padding_right=$PADDINGS \
	background.padding_right=$PADDINGS \
	background.padding_left=$PADDINGS \
	popup.background.border_width=2 \
	popup.background.corner_radius=11 \
	popup.background.border_color=$WHITE \
	popup.background.color=$BACKGROUND \
	popup.background.shadow.drawing=$SHADOW

source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

source "$ITEM_DIR/input.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/weather.sh"
source "$ITEM_DIR/network_down.sh"
source "$ITEM_DIR/network_up.sh"
source "$ITEM_DIR/disk.sh"
source "$ITEM_DIR/mem.sh"
source "$ITEM_DIR/cpu.sh"

sketchybar --update

echo "sketchybar configuration loaded.."
